[package]
name = "turtle"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.0.0"
image = "0.23.14"
rand = "0.8.4"
rayon = "1.5.1"
num-complex = "0.4.0"
cgmath = "0.18.0"